In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix,recall_score,accuracy_score,precision_score

In [2]:
data=pd.read_csv("iris.csv")
data.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:
X=data[['sepal_length','sepal_width','petal_length','petal_width']]
Y=data['species']

In [4]:
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.3)

In [5]:
nb=GaussianNB()
nb.fit(X_train,y_train)
y_pred=nb.predict(X_test)

In [6]:
print(y_pred)

['versicolor' 'setosa' 'versicolor' 'virginica' 'versicolor' 'versicolor'
 'virginica' 'virginica' 'versicolor' 'versicolor' 'setosa' 'virginica'
 'versicolor' 'setosa' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'setosa' 'virginica' 'setosa' 'setosa' 'versicolor'
 'versicolor' 'virginica' 'virginica' 'setosa' 'setosa' 'setosa'
 'versicolor' 'versicolor' 'virginica' 'versicolor' 'setosa' 'versicolor'
 'virginica' 'versicolor' 'virginica' 'setosa' 'virginica' 'virginica'
 'versicolor' 'virginica' 'versicolor']


In [12]:
cm=confusion_matrix(y_test,y_pred)
tn=cm[0][0]
fp=cm[0][1]
fn=cm[1][0]
tp=cm[1][1]

precision=precision_score(y_test,y_pred,average='macro')
accuracy=accuracy_score(y_test,y_pred)
error=1-accuracy
recall=recall_score(y_test,y_pred,average='macro')

print("confusion matrix\n",cm)
print("TP",tp,"FP",fp,"TN",tn,"FN",fn,"\n")
print("precision = %2f"%precision)
print("accuracy = %2f"%accuracy)
print("recall = %2f"%recall)
print("error rate = %2f"%error)



confusion matrix
 [[11  0  0]
 [ 0 20  0]
 [ 0  1 13]]
TP 20 FP 0 TN 11 FN 0 

precision = 0.984127
accuracy = 0.977778
recall = 0.976190
error rate = 0.022222
